on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

name: Continuous integration

env:
  CARGO_INCREMENTAL: 0

jobs:
  ci-windows:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ steps.rust-toolchain.outputs.cachekey }}-${{ hashFiles('**/Cargo.lock') }}

      - run: cargo build
      - run: cargo test
